os: osx
language: generic
osx_image: xcode10.1
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- export PATH=$PATH:`pwd`/flutter/bin
script:
- flutter doctor
- flutter packages get
- flutter test
deploy:
  provider: script
  script:
  - flutter test
  on:
    tags: true
cache:
  directories:
  - "$HOME/.pub-cache"
notifications:
  slack:
    secure: Ad3B3CR+CkGIktufI5JRUzvzXINOwjuL5LA5Jq+yP1zoZzWAM7/hB9hrLDA9ipJk7nzL2TzJc+NccasccrfPmEqBrduiw3vgD5+Nb6PXUuEc/oZKch2T2yr7RwAuQc2ORZGbFzbcHDOn+z2y2IWiZyTkzMRZbXhcFB7DWGVYEB1nazaKoDktHF1RF5Wl+qVUcEWVHX9dslF3HFKxvHHkFpjcWLFT/9qBbrD3tsZKpHf06teicYizmOeWHuFxwj3GbiVn5xm3nidwgmLn1EQ4TenQmnaBMWy/7SDHNTiXkBTC0hfLchqHIeMjgJolWQzy7iFkpUxTxJldbW4Crs2M12PLrN7/AmHWokS5SNDWkHGDyY3CjgJM8Uaw22m9jMLIKOQMhuV7i68MUnsiXJod+SLHGuKvoaQ00kV7cAQ1G0u3BKI0JLMUKQVsJCKW/rY7yL0OhZRK+W9rGoJG3/Y6EYT5SjRR094L+3WaHuR34wkofP2GTxp97aLur0zrZwPp6/md5FyRwGH09a67sruNFyuWEjAWZNNeLC5vw/guz/Lr5RDH+XxdhoiBA+dl5IA/H2ZZWCN5LjHh8m2DLfZCsc4F5isGlfqXQT3GMGpr4ZbvJZI5q6VFD7kI0lyXTkmUebIA4dr6REpx6QCKOANYLkVw65EG3gvbqCa+ukKIbAA=
